//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMRW
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_employee
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime appdate_time { get; set; }
        public int department_id { get; set; }
        public int level_id { get; set; }
    
        public virtual td_department td_department { get; set; }
        public virtual td_level td_level { get; set; }
    }
}
