//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMRW
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_maill
    {
        public int id { get; set; }
        public string maill { get; set; }
        public int contact_id { get; set; }
    
        public virtual td_contact td_contact { get; set; }
    }
}
